name: CI
on: push
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v3
      - name: Install node modules
        run: yarn
      - name: Build project
        run: yarn build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: dist
